[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "next start"

[variables]
NODE_ENV = "production"

# Disable cache mounts to prevent stale chunks
[build]
cacheDirectories = []